var data = {
    "posts": [
        {
            "id": 1,
            "title": "All of Those Products Are Making Your Skin Worse",
            "date": "5/30/2019",
            "category": "Health",
            "excerpt": "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
            "author": "Jane Doe",
            "price": 93.1,
            "sale_price": 30.94,
            "duration": null,
            "artist": null,
            "isBlog": "Yes",
            "isProduct": null,
            "isMovie": null,
            "isVideo": null
            }, {
            "id": 2,
            "title": "Young Women Are Leading The Global Climate Strike",
            "date": "8/3/2019",
            "category": "Culture",
            "excerpt": "In sagittis dui vel nisl. Duis ac nibh.",
            "author": "Jean E. Gustave",
            "price": 80.65,
            "sale_price": 35.79,
            "duration": null,
            "artist": null,
            "isBlog": "Yes",
            "isProduct": null,
            "isMovie": null,
            "isVideo": null
            }, {
            "id": 3,
            "title": "People Are Going to Save Us All From Office Life",
            "date": "5/27/2019",
            "category": "Science",
            "excerpt": "Suspendisse potenti. Nullam porttitor lacus at turpis.",
            "author": "Kenold Beauplan",
            "price": 82.9,
            "sale_price": 48.84,
            "duration": null,
            "artist": null,
            "isBlog": "Yes",
            "isProduct": null,
            "isMovie": null,
            "isVideo": null
            }, {
            "id": 4,
            "title": "The Top Milan Street Style Trends, From Leather To Mixed Prints",
            "date": "4/3/2019",
            "category": "Fashion",
            "excerpt": "Proin eu mi. Nulla ac enim.",
            "author": "John Smith",
            "price": 93.75,
            "sale_price": 42.15,
            "duration": null,
            "artist": null,
            "isBlog": "Yes",
            "isProduct": null,
            "isMovie": null,
            "isVideo": null
            }, {
            "id": 5,
            "title": "Strike Cobra 3d Legging",
            "date": "3/14/2019",
            "category": "Lingerie",
            "excerpt": "Praesent id massa id nisl venenatis lacinia.",
            "author": null,
            "price": 83.81,
            "sale_price": 41.29,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": "Yes",
            "isMovie": null,
            "isVideo": null
            }, {
            "id": 6,
            "title": "AE Denim Tie Front Crop Top",
            "date": "2/28/2019",
            "category": "Beauty",
            "excerpt": "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
            "author": null,
            "price": 96.92,
            "sale_price": 30.94,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": "Yes",
            "isMovie": null,
            "isVideo": null
            }, {
            "id": 7,
            "title": "Product 3",
            "date": "12/6/2018",
            "category": "Men",
            "excerpt": "Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
            "author": null,
            "price": 83.84,
            "sale_price": 49.4,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": "Yes",
            "isMovie": null,
            "isVideo": null
            }, {
            "id": 8,
            "title": "Product 4",
            "date": "9/22/2018",
            "category": "Women",
            "excerpt": "Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
            "author": null,
            "price": 90.1,
            "sale_price": 33.02,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": "Yes",
            "isMovie": null,
            "isVideo": null
            }, {
            "id": 11,
            "title": "Dumb and Dummer",
            "date": "11/26/2018",
            "category": null,
            "excerpt": "Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
            "author": null,
            "price": 84.91,
            "sale_price": 40.44,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": null,
            "isMovie": "Yes",
            "isVideo": null
            }, {
            "id": 12,
            "title": "Shaft",
            "date": "8/15/2019",
            "category": null,
            "excerpt": "Integer ac leo.",
            "author": null,
            "price": 85.89,
            "sale_price": 42.44,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": null,
            "isMovie": "Yes",
            "isVideo": null
            }, {
            "id": 13,
            "title": "Criminal Mind",
            "date": "6/29/2019",
            "category": null,
            "excerpt": "Etiam faucibus cursus urna. Ut tellus.",
            "author": null,
            "price": 93.09,
            "sale_price": 44.53,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": null,
            "isMovie": "Yes",
            "isVideo": null
            }, {
            "id": 14,
            "title": "Friday Night",
            "date": "3/31/2019",
            "category": null,
            "excerpt": "Nam nulla.",
            "author": null,
            "price": 91.2,
            "sale_price": 36.08,
            "duration": "4:23",
            "artist": "Katty Perry",
            "isBlog": null,
            "isProduct": null,
            "isMovie": null,
            "isVideo": "Yes"
            }, {
            "id": 15,
            "title": "Umbrella",
            "date": "2/26/2019",
            "category": null,
            "excerpt": "Curabitur convallis.",
            "author": null,
            "price": 84.73,
            "sale_price": 49.05,
            "duration": "3:23",
            "artist": "Rihanna",
            "isBlog": null,
            "isProduct": null,
            "isMovie": null,
            "isVideo": "Yes"
            }, {
            "id": 16,
            "title": "You Need to Calm Down",
            "date": "5/24/2019",
            "category": null,
            "excerpt": "Curabitur in libero ut massa volutpat convallis.",
            "author": null,
            "price": 82.96,
            "sale_price": 39.79,
            "duration": "4:32",
            "artist": "Taylor Swift",
            "isBlog": null,
            "isProduct": null,
            "isMovie": null,
            "isVideo": "Yes"
            }, {
            "id": 17,
            "title": "Put a Ring On It",
            "date": "6/26/2019",
            "category": null,
            "excerpt": "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
            "author": null,
            "price": 99.87,
            "sale_price": 38.36,
            "duration": "5:15",
            "artist": "Beyonce",
            "isBlog": null,
            "isProduct": null,
            "isMovie": null,
            "isVideo": "Yes"
        }, {
            "id": 18,
            "title": "Paris",
            "date": "6/26/2019",
            "category": null,
            "excerpt": "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
            "author": null,
            "price": 450,
            "sale_price": 38.36,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": null,
            "isMovie": null,
            "isVideo": null,
            "isTour": "Yes"
        }, {
            "id": 19,
            "title": "New York",
            "date": "6/26/2019",
            "category": null,
            "excerpt": "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
            "author": null,
            "price": 99,
            "sale_price": 38.36,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": null,
            "isMovie": null,
            "isVideo": null,
            "isTour": "Yes"
        },{
            "id": 21,
            "title": "Mexico",
            "date": "6/26/2019",
            "category": null,
            "excerpt": "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
            "author": null,
            "price": 325,
            "sale_price": 38.36,
            "duration": null,
            "artist": null,
            "isBlog": null,
            "isProduct": null,
            "isMovie": null,
            "isVideo": null,
            "isTour": "Yes"
        }
    ]
}

$(document).ready(function() {
    // register handlebarsIntl helper
    HandlebarsIntl.registerWith(Handlebars);

    var dataTemplate = $("#data-template").html();
    var compiledDataTemplate = Handlebars.compile(dataTemplate);
    $(".data-list-container").html(compiledDataTemplate(data));

});